name: Build, package and release the CAI Chatbot web part solution
on:
 push:
   branches: [master]
jobs:
  build-package-release:
    name: Build, package and release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js 14.17.1 LTS
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Run npm ci
        run: npm ci
      - name: Build and release solution
        run: npm run release
      - name: Upload the released solution
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "CAI Chatbot web part"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            README.md
            *.sppkg
